# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
# Copyright (C) 2019 Northwestern University.
#
# Invenio App RDM is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

FROM postgres:9.6
COPY ./init-app-db.sh /docker-entrypoint-initdb.d/10-init-app-db.sh
