# SPDX-FileCopyrightText: 2019 CERN.
# SPDX-FileCopyrightText: 2019 Northwestern University.
# SPDX-FileCopyrightText: 2022 Graz University of Technology.
# SPDX-License-Identifier: MIT

# Extraction from Python source files
[python: **.py]
encoding = utf-8

# Extraction from Jinja2 templates
[jinja2: **/templates/**.html]
encoding = utf-8
